import "server-only";
import type {
  Household,
  Timeseries,
  TimeseriesRecord,
  Tariff,
  SpotPrice,
  MonthlyBill,
  InsightEvent,
  Snapshot,
} from "./types";
import type { WeatherOutlook, DayForecast, SkyIcon } from "./weather";
import { POPULAR_QUESTIONS } from "./questions";

// The synthetic dataset is for the year 2025. We anchor a fixed "now" so the
// live view always shows an interesting summer-midday moment for the demo.
export const REFERENCE_NOW = "2025-06-20T13:00:00";

// ---- data source: the enpal backend -----------------------------------------
// The frontend keeps no dataset of its own, every byte is fetched from the
// enpal server's raw-data API. Point ENPAL_API_URL at the backend (defaults to
// the local dev server). All the computation below is unchanged; only the
// *source* of the raw JSON moved from local files to the server.

const API_BASE = (
  process.env.ENPAL_API_URL ?? "http://localhost:8000/api/v1"
).replace(/\/$/, "");

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, { cache: "no-store" });
  if (!res.ok) {
    throw new Error(
      `Enpal API ${path} failed: ${res.status} ${res.statusText}. ` +
        `Is the backend running at ${API_BASE}?`
    );
  }
  return (await res.json()) as T;
}

/**
 * Ensure the reference data (and, when an id is given, that household's
 * timeseries) is loaded from the backend into the in-memory caches. Call this
 * and `await` it before invoking any of the synchronous accessors/derived
 * views below. Cheap to call repeatedly, each dataset is fetched once.
 */
export async function ensureData(id?: string): Promise<void> {
  if (!_households) {
    const [households, tariffs, bills, insights, prices] =
      await Promise.all([
        fetchJson<Household[]>("/data/households"),
        fetchJson<Tariff[]>("/data/tariffs"),
        fetchJson<MonthlyBill[]>("/data/monthly_bills"),
        fetchJson<InsightEvent[]>("/data/insight_events"),
        fetchJson<{ prices: SpotPrice[] }>("/data/dynamic_prices"),
      ]);
    _households = households;
    _tariffs = tariffs;
    _bills = bills;
    _insights = insights;
    _prices = prices.prices;
  }
  if (id && !_timeseries.has(id)) {
    _timeseries.set(id, await fetchJson<Timeseries>(`/data/timeseries/${id}`));
  }
}

// ---- chatbot: profile-based suggested questions (from the enpal server) ------

export interface SuggestedQuestion {
  id: string;
  text: string;
  source: string; // "profile" | "popular"
}

/**
 * Pre-defined questions for a household, generated by the enpal chat service
 * from that household's own profile (assets, tariff, anomalies). Falls back to
 * the static popular list if the backend is unreachable.
 */
export async function getSuggestedQuestions(id: string): Promise<SuggestedQuestion[]> {
  try {
    const data = await fetchJson<{ questions: SuggestedQuestion[] }>(
      `/chat/suggested-questions?household_id=${encodeURIComponent(id)}`
    );
    if (data?.questions?.length) return data.questions;
  } catch (err) {
    console.error("suggested-questions fetch failed, using fallback:", err);
  }
  return POPULAR_QUESTIONS.map((q, i) => ({
    id: `popular-${i}`,
    text: q.q,
    source: "popular",
  }));
}

function loaded<T>(value: T | null, what: string): T {
  if (value === null) {
    throw new Error(`${what} not loaded, call \`await ensureData()\` first.`);
  }
  return value;
}

// ---- cached accessors (synchronous; populated by ensureData) -----------------

let _households: Household[] | null = null;
export function getHouseholds(): Household[] {
  return loaded(_households, "households");
}

export function getHousehold(id: string): Household {
  const h = getHouseholds().find((x) => x.household_id === id);
  if (!h) throw new Error(`Unknown household ${id}`);
  return h;
}

let _tariffs: Tariff[] | null = null;
export function getTariffs(): Tariff[] {
  return loaded(_tariffs, "tariffs");
}
export function getTariff(id: string): Tariff {
  const t = getTariffs().find((x) => x.tariff_id === id);
  if (!t) throw new Error(`Unknown tariff ${id}`);
  return t;
}

let _bills: MonthlyBill[] | null = null;
export function getAllBills(): MonthlyBill[] {
  return loaded(_bills, "monthly bills");
}
export function getBills(id: string): MonthlyBill[] {
  return getAllBills()
    .filter((b) => b.household_id === id)
    .sort((a, b) => a.month.localeCompare(b.month));
}

let _insights: InsightEvent[] | null = null;
export function getAllInsights(): InsightEvent[] {
  return loaded(_insights, "insight events");
}
export function getInsights(id: string): InsightEvent[] {
  return getAllInsights().filter((i) => i.household_id === id);
}

let _prices: SpotPrice[] | null = null;
export function getSpotPrices(): SpotPrice[] {
  return loaded(_prices, "spot prices");
}

const _timeseries = new Map<string, Timeseries>();
export function getTimeseries(id: string): Timeseries {
  const ts = _timeseries.get(id);
  if (!ts) {
    throw new Error(
      `Timeseries for ${id} not loaded, call \`await ensureData("${id}")\` first.`
    );
  }
  return ts;
}

// ---- helpers -----------------------------------------------------------------

const STEP_HOURS = 0.25; // 15-minute resolution -> kWh = kW * 0.25

/** Index of the record at-or-just-before the given timestamp. */
function recordIndexAt(records: TimeseriesRecord[], timestamp: string): number {
  // records are chronological; binary search on ISO string compare
  let lo = 0;
  let hi = records.length - 1;
  let ans = 0;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (records[mid].timestamp <= timestamp) {
      ans = mid;
      lo = mid + 1;
    } else {
      hi = mid - 1;
    }
  }
  return ans;
}

// ---- derived views -----------------------------------------------------------

export function getSnapshot(id: string, timestamp = REFERENCE_NOW): Snapshot {
  const { records } = getTimeseries(id);
  const rec = records[recordIndexAt(records, timestamp)];

  const consumption = rec.total_consumption_kw;
  const solarToLoad = Math.min(rec.pv_production_kw, consumption);
  const solar_coverage_pct =
    consumption > 0 ? Math.min(100, (solarToLoad / consumption) * 100) : 100;

  let status: Snapshot["status"];
  if (rec.grid_export_kw > 0.05) status = "exporting";
  else if (rec.battery_discharge_kw > 0.05 && rec.grid_import_kw < 0.05)
    status = "battery_powered";
  else if (rec.grid_import_kw > 0.05) status = "importing";
  else status = "self_powered";

  const headline = buildHeadline(rec, status, solar_coverage_pct);

  return {
    timestamp: rec.timestamp,
    outdoor_temp_c: rec.outdoor_temp_c,
    pv_production_kw: rec.pv_production_kw,
    house_load_kw: rec.house_load_kw,
    heatpump_kw: rec.heatpump_kw,
    ev_charging_kw: rec.ev_charging_kw,
    total_consumption_kw: rec.total_consumption_kw,
    battery_charge_kw: rec.battery_charge_kw,
    battery_discharge_kw: rec.battery_discharge_kw,
    battery_soc_pct: rec.battery_soc_pct,
    battery_soc_kwh: rec.battery_soc_kwh,
    grid_import_kw: rec.grid_import_kw,
    grid_export_kw: rec.grid_export_kw,
    price_eur_per_kwh: rec.price_eur_per_kwh,
    solar_coverage_pct,
    status,
    headline,
  };
}

function buildHeadline(
  rec: TimeseriesRecord,
  status: Snapshot["status"],
  coverage: number
): string {
  switch (status) {
    case "exporting":
      return `Your panels are producing more than the home needs, the surplus is ${
        rec.battery_charge_kw > 0.05 ? "charging your battery and " : ""
      }flowing to the grid for credit.`;
    case "battery_powered":
      return `Your home is running on stored solar from the battery right now, no grid power needed.`;
    case "self_powered":
      return `Solar is covering your home directly, you're running clean and free at the moment.`;
    case "importing":
    default:
      return coverage > 5
        ? `Solar is covering about ${Math.round(
            coverage
          )}% of your home right now; the rest comes from the grid.`
        : `Your home is drawing from the grid right now, little or no solar at this moment.`;
  }
}

export interface DaySummary {
  date: string;
  pv_kwh: number;
  consumption_kwh: number;
  grid_import_kwh: number;
  grid_export_kwh: number;
  self_sufficiency_pct: number;
  cost_eur: number;
  feed_in_credit_eur: number;
  net_cost_eur: number;
  avg_outdoor_temp_c: number;
}

export function getDaySummary(id: string, date = REFERENCE_NOW.slice(0, 10)): DaySummary {
  const { records } = getTimeseries(id);
  const tariff = getTariff(getHousehold(id).tariff_id);
  const day = records.filter((r) => r.timestamp.startsWith(date));

  let pv = 0,
    cons = 0,
    imp = 0,
    exp = 0,
    cost = 0,
    temp = 0;
  for (const r of day) {
    pv += r.pv_production_kw * STEP_HOURS;
    cons += r.total_consumption_kw * STEP_HOURS;
    imp += r.grid_import_kw * STEP_HOURS;
    exp += r.grid_export_kw * STEP_HOURS;
    cost += r.grid_import_kw * STEP_HOURS * r.price_eur_per_kwh;
    temp += r.outdoor_temp_c;
  }
  const credit = exp * tariff.feed_in_eur_per_kwh;
  const selfUse = cons - imp;
  return {
    date,
    pv_kwh: round(pv),
    consumption_kwh: round(cons),
    grid_import_kwh: round(imp),
    grid_export_kwh: round(exp),
    self_sufficiency_pct: cons > 0 ? round((selfUse / cons) * 100, 1) : 0,
    cost_eur: round(cost),
    feed_in_credit_eur: round(credit),
    net_cost_eur: round(cost - credit),
    avg_outdoor_temp_c: day.length ? round(temp / day.length, 1) : 0,
  };
}

/** Cheapest upcoming hours (today, from `from` onward) for shifting flexible loads. */
export interface PriceWindow {
  time: string; // HH:mm
  price: number;
  rank: number;
}
export function getCheapestWindows(
  id: string,
  from = REFERENCE_NOW,
  count = 3
): PriceWindow[] {
  const { records } = getTimeseries(id);
  const date = from.slice(0, 10);
  // hourly average prices for the rest of the day
  const byHour = new Map<string, { sum: number; n: number }>();
  for (const r of records) {
    if (!r.timestamp.startsWith(date)) continue;
    if (r.timestamp < from) continue;
    const hh = r.timestamp.slice(11, 13);
    const cur = byHour.get(hh) ?? { sum: 0, n: 0 };
    cur.sum += r.price_eur_per_kwh;
    cur.n += 1;
    byHour.set(hh, cur);
  }
  const hours = [...byHour.entries()]
    .map(([hh, { sum, n }]) => ({ time: `${hh}:00`, price: round(sum / n, 4) }))
    .sort((a, b) => a.price - b.price)
    .slice(0, count)
    .map((w, i) => ({ ...w, rank: i + 1 }));
  return hours;
}

// ---- where is the home's power coming from right now? ------------------------

export interface PowerSource {
  key: "solar" | "battery" | "grid";
  label: string;
  pct: number;
}

export interface PowerMix {
  sources: PowerSource[]; // sorted high -> low, only shares >= 5%
  summary: string; // e.g. "80% solar · 20% grid"
  headline: string; // e.g. "Running on solar" / "Mostly from the grid"
}

/** Breaks the home's *current electricity* into solar / battery / grid shares. */
export function getPowerMix(id: string, timestamp = REFERENCE_NOW): PowerMix {
  const snap = getSnapshot(id, timestamp);
  const cons = snap.total_consumption_kw;
  if (cons < 0.02) {
    return { sources: [], summary: "barely using any power", headline: "Home is idle" };
  }
  const grid = Math.min(snap.grid_import_kw, cons);
  const battery = Math.min(snap.battery_discharge_kw, Math.max(0, cons - grid));
  const solar = Math.max(0, cons - grid - battery);

  const raw: PowerSource[] = [
    { key: "solar", label: "solar", pct: (solar / cons) * 100 },
    { key: "battery", label: "battery", pct: (battery / cons) * 100 },
    { key: "grid", label: "grid", pct: (grid / cons) * 100 },
  ];
  const sources = raw
    .filter((s) => s.pct >= 5)
    .map((s) => ({ ...s, pct: Math.round(s.pct) }))
    .sort((a, b) => b.pct - a.pct);

  const summary = sources.map((s) => `${s.pct}% ${s.label}`).join(" · ");

  // plain-language headline from the dominant source(s)
  const top = sources[0];
  let headline: string;
  if (!top) headline = "Home is idle";
  else if (top.key === "solar" && top.pct >= 85) headline = "Running on solar";
  else if (top.key === "battery" && top.pct >= 70) headline = "Running on your battery";
  else if (top.key === "grid" && top.pct >= 70) headline = "Mostly from the grid";
  else if (sources.length >= 2)
    headline = `${cap(top.label)} + ${sources[1].label}`;
  else headline = `Running on ${top.label}`;

  return { sources, summary, headline };
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ---- traffic-light "should I use power now?" --------------------------------

export type TrafficLight = "green" | "yellow" | "red";

export interface TrafficStatus {
  light: TrafficLight;
  title: string;
  reason: string;
  price_now: number;
  price_cents: number;
  best_window: string; // HH:mm
  best_price: number;
  solar_surplus: boolean;
  mix: PowerMix; // where the home's electricity is coming from now
}

export function getTrafficStatus(id: string, timestamp = REFERENCE_NOW): TrafficStatus {
  const snap = getSnapshot(id, timestamp);
  const { records } = getTimeseries(id);
  const date = timestamp.slice(0, 10);
  const dayPrices = records
    .filter((r) => r.timestamp.startsWith(date))
    .map((r) => r.price_eur_per_kwh);
  const min = Math.min(...dayPrices);
  const max = Math.max(...dayPrices);
  const span = Math.max(max - min, 0.0001);
  const lo = min + span / 3;
  const hi = min + (2 * span) / 3;
  const p = snap.price_eur_per_kwh;
  const surplus = snap.grid_export_kw > 0.1 || snap.solar_coverage_pct > 90;

  let light: TrafficLight;
  if (surplus || p <= lo) light = "green";
  else if (p <= hi) light = "yellow";
  else light = "red";

  const [best] = getCheapestWindows(id, timestamp, 1);
  const mix = getPowerMix(id, timestamp);

  // Titles are about electricity overall (any source), not solar specifically.
  const titles: Record<TrafficLight, string> = {
    green: "Great time to use power",
    yellow: "An okay time to use power",
    red: "Pricey right now, better to wait",
  };
  const reasons: Record<TrafficLight, string> = {
    green: surplus
      ? `Your home is running on free solar${
          mix.sources.some((s) => s.key === "battery") ? " and stored battery power" : ""
        } right now, using power costs you almost nothing.`
      : `Electricity is cheap right now (${(p * 100).toFixed(
          1
        )}c/kWh). A good moment to run the dishwasher, laundry or charge the car.`,
    yellow: `Electricity is mid-priced right now (${(p * 100).toFixed(
      1
    )}c/kWh). Fine for essentials${best ? `, but ${best.time} is cheaper today.` : "."}`,
    red: `Electricity is expensive right now (${(p * 100).toFixed(1)}c/kWh)${
      best ? `, wait until around ${best.time} (${(best.price * 100).toFixed(1)}c/kWh) to save.` : "."
    }`,
  };

  return {
    light,
    title: titles[light],
    reason: reasons[light],
    price_now: snap.price_eur_per_kwh,
    price_cents: round(snap.price_eur_per_kwh * 100, 1),
    best_window: best?.time ?? "13:00",
    best_price: best?.price ?? p,
    solar_surplus: surplus,
    mix,
  };
}

// ---- overall energy health ("are we good / warning / high alert?") -----------

export type HealthLevel = "great" | "warning" | "alert";

export interface EnergyHealth {
  level: HealthLevel;
  badge: string; // "All good" | "Warning" | "High alert"
  title: string;
  reason: string;
  consumption_kw: number;
  self_sufficiency_pct: number;
  price_cents: number;
}

/**
 * The home's overall energy condition right now, a single great / warning /
 * high-alert read based on how much it's drawing, how much of that is
 * self-supplied, how pricey the grid is, and any active device anomalies.
 */
export function getEnergyHealth(id: string, timestamp = REFERENCE_NOW): EnergyHealth {
  const snap = getSnapshot(id, timestamp);
  const { records } = getTimeseries(id);
  const date = timestamp.slice(0, 10);

  const cons = snap.total_consumption_kw;
  const selfSuff = cons > 0 ? Math.max(0, Math.min(1, (cons - snap.grid_import_kw) / cons)) : 1;

  // Typical "high" load = 95th percentile of the year's consumption.
  const sorted = records.map((r) => r.total_consumption_kw).sort((a, b) => a - b);
  const p95 = sorted[Math.floor(sorted.length * 0.95)] || 1;
  const load = p95 > 0 ? cons / p95 : 0;

  // Where the current price sits within today's range.
  const dayPrices = records
    .filter((r) => r.timestamp.startsWith(date))
    .map((r) => r.price_eur_per_kwh);
  const min = Math.min(...dayPrices);
  const max = Math.max(...dayPrices);
  const priceTier = (snap.price_eur_per_kwh - min) / Math.max(max - min, 1e-4);

  // Active device anomalies on this date.
  const anomalies = getInsights(id).filter((e) => {
    if (e.type !== "anomaly") return false;
    const [s, en] = e.period.split("..");
    return s && en && date >= s && date <= en;
  });
  const highAnomaly = anomalies.some((a) => a.severity === "high");

  const gridHeavy = selfSuff < 0.4;
  const expensive = priceTier > 0.66;

  let level: HealthLevel = "great";
  if (highAnomaly || (load > 0.85 && gridHeavy)) level = "alert";
  else if (anomalies.length > 0 || load > 0.6 || (gridHeavy && expensive)) level = "warning";

  const consTxt = `${cons.toFixed(1)} kW`;
  const ssTxt = `${Math.round(selfSuff * 100)}%`;

  let badge: string, title: string, reason: string;
  if (level === "alert") {
    badge = "High alert";
    if (highAnomaly) {
      title = "High alert, a device needs attention";
      reason = `${anomalies.find((a) => a.severity === "high")!.title}. It's pushing your usage well above normal, worth checking right now.`;
    } else {
      title = "High alert, heavy, expensive usage";
      reason = `Your home is drawing ${consTxt} (near its peak) and mostly from the grid (only ${ssTxt} self-supplied). This is a costly way to run, pause or shift heavy loads.`;
    }
  } else if (level === "warning") {
    badge = "Warning";
    title = "Worth a look, usage is climbing";
    reason =
      anomalies.length > 0
        ? `${anomalies[0].title}. Keep an eye on it.`
        : `You're using ${consTxt}${gridHeavy ? ` and leaning on the grid (${ssTxt} self-supplied)` : ""}. Move flexible loads to sunny or cheap hours to bring it back down.`;
  } else {
    badge = "All good";
    title = "Your energy is running great";
    reason = `Using ${consTxt}, with ${ssTxt} coming from your own solar and battery. Everything's healthy right now.`;
  }

  return {
    level,
    badge,
    title,
    reason,
    consumption_kw: round(cons),
    self_sufficiency_pct: Math.round(selfSuff * 100),
    price_cents: round(snap.price_eur_per_kwh * 100, 1),
  };
}

// ---- monthly saved vs. paid --------------------------------------------------

export interface MonthSummary {
  month: string;
  paid_eur: number; // total bill
  saved_eur: number; // solar self-consumption value + feed-in credit
  saved_from_solar_eur: number;
  feed_in_credit_eur: number;
  self_consumed_kwh: number;
  self_sufficiency_pct: number;
  bill_without_solar_eur: number; // what the bill would have been
}

export function getMonthSummary(id: string, month = REFERENCE_NOW.slice(0, 7)): MonthSummary {
  const bills = getBills(id);
  const b = bills.find((x) => x.month === month) ?? bills[bills.length - 1];
  const selfConsumed = Math.max(0, b.consumption_kwh - b.grid_import_kwh);
  // effective per-kWh rate the household actually pays for imported power
  const importRate = b.grid_import_kwh > 0 ? b.energy_cost_eur / b.grid_import_kwh : 0.3;
  const savedFromSolar = selfConsumed * importRate;
  const saved = savedFromSolar + b.feed_in_credit_eur;
  return {
    month: b.month,
    paid_eur: round(b.total_bill_eur),
    saved_eur: round(saved),
    saved_from_solar_eur: round(savedFromSolar),
    feed_in_credit_eur: round(b.feed_in_credit_eur),
    self_consumed_kwh: round(selfConsumed),
    self_sufficiency_pct: b.self_sufficiency_pct,
    bill_without_solar_eur: round(b.total_bill_eur + saved),
  };
}

/** Last N months of saved/paid for a mini trend. */
export function getMonthlyTrend(id: string, months = 6): MonthSummary[] {
  const all = getBills(id).map((b) => getMonthSummary(id, b.month));
  const nowMonth = REFERENCE_NOW.slice(0, 7);
  const idx = all.findIndex((m) => m.month === nowMonth);
  const end = idx >= 0 ? idx + 1 : all.length;
  return all.slice(Math.max(0, end - months), end);
}

// ---- bill so far this month + likely total -----------------------------------

export interface MonthToDate {
  month: string;
  so_far_eur: number;
  likely_total_eur: number;
  days_elapsed: number;
  days_in_month: number;
}

export function getMonthToDate(id: string, timestamp = REFERENCE_NOW): MonthToDate {
  const { records } = getTimeseries(id);
  const tariff = getTariff(getHousehold(id).tariff_id);
  const month = timestamp.slice(0, 7);
  const day = Number(timestamp.slice(8, 10));
  const daysInMonth = new Date(Number(month.slice(0, 4)), Number(month.slice(5, 7)), 0).getDate();

  let energy = 0;
  let credit = 0;
  for (const r of records) {
    if (!r.timestamp.startsWith(month)) continue;
    if (r.timestamp > timestamp) break;
    energy += r.grid_import_kw * STEP_HOURS * r.price_eur_per_kwh;
    credit += r.grid_export_kw * STEP_HOURS * tariff.feed_in_eur_per_kwh;
  }
  const baseSoFar = (tariff.base_fee_eur_per_month * day) / daysInMonth;
  const soFar = energy - credit + baseSoFar;
  // simple linear projection to month end
  const likely = day > 0 ? (soFar / day) * daysInMonth : soFar;
  return {
    month,
    so_far_eur: round(Math.max(0, soFar)),
    likely_total_eur: round(Math.max(0, likely)),
    days_elapsed: day,
    days_in_month: daysInMonth,
  };
}

// ---- this month vs the last two months --------------------------------------

export interface BillComparison {
  projected_eur: number; // this month's likely total
  prev_avg_eur: number; // average bill of the previous two months
  delta_eur: number; // prev_avg - projected (positive => cheaper now = good)
  verdict: "better" | "worse" | "similar";
}

export function getBillComparison(id: string, month = REFERENCE_NOW.slice(0, 7)): BillComparison {
  const bills = getBills(id);
  const idx = bills.findIndex((b) => b.month === month);
  const projected = getMonthToDate(id).likely_total_eur;
  const prev = idx > 0 ? bills.slice(Math.max(0, idx - 2), idx) : [];
  const prevAvg = prev.length
    ? prev.reduce((a, b) => a + b.total_bill_eur, 0) / prev.length
    : projected;
  const delta = round(prevAvg - projected);
  const verdict: BillComparison["verdict"] =
    Math.abs(delta) < prevAvg * 0.05 ? "similar" : delta > 0 ? "better" : "worse";
  return {
    projected_eur: projected,
    prev_avg_eur: round(prevAvg),
    delta_eur: delta,
    verdict,
  };
}

// ---- per-day savings (last N days) ------------------------------------------

export interface DailySaving {
  date: string;
  weekday: string;
  saved_eur: number;
}

export function getDailySavings(id: string, end = REFERENCE_NOW.slice(0, 10), days = 7): DailySaving[] {
  const out: DailySaving[] = [];
  const endDate = new Date(end + "T00:00:00");
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(endDate);
    d.setDate(d.getDate() - i);
    const iso = d.toISOString().slice(0, 10);
    const s = getDaySummary(id, iso);
    const selfConsumed = Math.max(0, s.consumption_kwh - s.grid_import_kwh);
    const importRate = s.grid_import_kwh > 0 ? s.cost_eur / s.grid_import_kwh : 0.3;
    const saved = selfConsumed * importRate + s.feed_in_credit_eur;
    out.push({
      date: iso,
      weekday: d.toLocaleDateString("en-US", { weekday: "short" }),
      saved_eur: round(saved),
    });
  }
  return out;
}

// ---- equipment status (per device, condition colour) -------------------------

export type Condition = "green" | "amber" | "grey";

export interface EquipmentUnit {
  key: "solar" | "battery" | "heatpump" | "ev" | "battery_suggestion";
  name: string;
  status: string; // short plain-language line
  condition: Condition;
  why: string; // longer explanation for the detail screen
  // Money impact of this device (savers are positive savings; consumers are cost).
  today_eur?: number;
  month_eur?: number;
  impact?: "saving" | "cost";
}

interface UnitMoney {
  today_eur: number;
  month_eur: number;
  impact: "saving" | "cost";
}

/**
 * Per-device money impact, today and month-to-date.
 *  - Solar: value of generation used at home (avoids buying) + feed-in for export.
 *  - Battery: value of stored energy discharged (kWh you didn't buy back).
 *  - Heat pump / EV: what they cost to run at the live price.
 */
export function getEquipmentEconomics(
  id: string,
  timestamp = REFERENCE_NOW
): Record<string, UnitMoney> {
  const { records } = getTimeseries(id);
  const date = timestamp.slice(0, 10);
  const month = timestamp.slice(0, 7);
  const importRate = avgImportRate(id);
  const feedRate = getTariff(getHousehold(id).tariff_id).feed_in_eur_per_kwh;

  const acc = {
    pvSelfD: 0, exportD: 0, battD: 0, hpCostD: 0, evCostD: 0,
    pvSelfM: 0, exportM: 0, battM: 0, hpCostM: 0, evCostM: 0,
  };
  for (const r of records) {
    if (!r.timestamp.startsWith(month) || r.timestamp > timestamp) continue;
    const solarToLoad = Math.min(r.pv_production_kw, r.total_consumption_kw) * STEP_HOURS;
    const exp = r.grid_export_kw * STEP_HOURS;
    const batt = r.battery_discharge_kw * STEP_HOURS;
    const hpCost = r.heatpump_kw * STEP_HOURS * r.price_eur_per_kwh;
    const evCost = r.ev_charging_kw * STEP_HOURS * r.price_eur_per_kwh;
    acc.pvSelfM += solarToLoad; acc.exportM += exp; acc.battM += batt;
    acc.hpCostM += hpCost; acc.evCostM += evCost;
    if (r.timestamp.startsWith(date)) {
      acc.pvSelfD += solarToLoad; acc.exportD += exp; acc.battD += batt;
      acc.hpCostD += hpCost; acc.evCostD += evCost;
    }
  }

  return {
    solar: {
      today_eur: round(acc.pvSelfD * importRate + acc.exportD * feedRate),
      month_eur: round(acc.pvSelfM * importRate + acc.exportM * feedRate),
      impact: "saving",
    },
    battery: {
      today_eur: round(acc.battD * importRate),
      month_eur: round(acc.battM * importRate),
      impact: "saving",
    },
    heatpump: {
      today_eur: round(acc.hpCostD),
      month_eur: round(acc.hpCostM),
      impact: "cost",
    },
    ev: {
      today_eur: round(acc.evCostD),
      month_eur: round(acc.evCostM),
      impact: "cost",
    },
  };
}

function anomalyActive(id: string, unit: string, date: string): boolean {
  return getInsights(id).some((e) => {
    if (e.type !== "anomaly") return false;
    if (!e.title.toLowerCase().includes(unit)) return false;
    const [start, endP] = e.period.split("..");
    return start && endP && date >= start && date <= endP;
  });
}

export function getEquipment(id: string, timestamp = REFERENCE_NOW): EquipmentUnit[] {
  const h = getHousehold(id);
  const snap = getSnapshot(id, timestamp);
  const date = timestamp.slice(0, 10);
  const units: EquipmentUnit[] = [];

  // Solar
  if (h.pv_kwp > 0) {
    const on = snap.pv_production_kw > 0.1;
    units.push({
      key: "solar",
      name: "Solar",
      status: on ? `making ${snap.pv_production_kw.toFixed(1)} kW` : "not producing now",
      condition: on ? "green" : "grey",
      why: on
        ? `Your roof is generating ${snap.pv_production_kw.toFixed(
            1
          )} kW right now, covering your home and topping up the rest.`
        : `It's dark or overcast, so the panels aren't producing at the moment. Normal outside daylight hours.`,
    });
  }

  // Battery (or a suggestion card if there is none)
  if (h.battery_kwh > 0) {
    const charging = snap.battery_charge_kw > 0.05;
    const discharging = snap.battery_discharge_kw > 0.05;
    units.push({
      key: "battery",
      name: "Battery",
      status: `${Math.round(snap.battery_soc_pct)}% full${
        charging ? " · charging" : discharging ? " · in use" : ""
      }`,
      condition: "green",
      why: charging
        ? `Your battery is storing spare solar now (${Math.round(
            snap.battery_soc_pct
          )}% full) to power the house this evening.`
        : discharging
        ? `Your battery is powering the home right now from stored solar (${Math.round(
            snap.battery_soc_pct
          )}% left).`
        : `Your battery is holding ${Math.round(snap.battery_soc_pct)}% charge, ready for when you need it.`,
    });
  } else {
    const rec = getBatteryRecommendation(id);
    units.push({
      key: "battery_suggestion",
      name: "Battery",
      status: rec ? `add one · save ~€${rec.annual_eur}/yr` : "not installed",
      condition: "grey",
      why: rec
        ? `You don't have a home battery yet. Right now your spare solar is sold to the grid cheaply. A battery would store it for the evening, saving roughly €${rec.annual_eur} a year.`
        : `You don't have a home battery installed.`,
    });
  }

  // Heat pump
  if (h.heat_pump) {
    const amber = anomalyActive(id, "heat pump", date);
    const on = snap.heatpump_kw > 0.2;
    units.push({
      key: "heatpump",
      name: "Heat pump",
      status: amber ? "worth a look" : on ? `heating · ${snap.heatpump_kw.toFixed(1)} kW` : "resting",
      condition: amber ? "amber" : on ? "green" : "grey",
      why: amber
        ? `Your heat pump has been using more power than the weather explains. That's usually a setting or a service issue, worth a quick check, but nothing urgent.`
        : on
        ? `Your heat pump is running normally, drawing ${snap.heatpump_kw.toFixed(1)} kW to keep the home warm.`
        : `It's warm enough that your heat pump is resting right now, using little or no power.`,
    });
  }

  // EV
  if (h.ev_charger) {
    const charging = snap.ev_charging_kw > 0.1;
    units.push({
      key: "ev",
      name: "Car",
      status: charging ? `charging · ${snap.ev_charging_kw.toFixed(1)} kW` : "not charging",
      condition: charging ? "green" : "grey",
      why: charging
        ? `Your car is charging at ${snap.ev_charging_kw.toFixed(1)} kW right now.`
        : `Your car isn't charging at the moment. The app will suggest the cheapest window when you need it.`,
    });
  }

  // Attach each device's money impact (today + month-to-date).
  const econ = getEquipmentEconomics(id, timestamp);
  for (const u of units) {
    const e = econ[u.key];
    if (e) {
      u.today_eur = e.today_eur;
      u.month_eur = e.month_eur;
      u.impact = e.impact;
    }
  }

  return units;
}

// ---- "money on the table" battery recommendation -----------------------------

export interface BatteryRecommendation {
  annual_eur: number;
  exported_kwh: number;
  suggested_kwh: number;
}

/** For homes WITHOUT a battery: estimated yearly saving from adding one. */
export function getBatteryRecommendation(id: string): BatteryRecommendation | null {
  const h = getHousehold(id);
  if (h.battery_kwh > 0) return null;
  const bills = getBills(id);
  const tariff = getTariff(h.tariff_id);
  const exportKwh = bills.reduce((a, b) => a + b.grid_export_kwh, 0);
  const importCost = bills.reduce((a, b) => a + b.energy_cost_eur, 0);
  const importKwh = bills.reduce((a, b) => a + b.grid_import_kwh, 0);
  const importRate = importKwh > 0 ? importCost / importKwh : 0.3;

  // A battery stores spare solar to use later instead of buying it back. The energy
  // it can actually recover is bounded by BOTH the surplus you export and the power
  // you later import, you can't avoid buying more than you actually buy. A ~0.7
  // factor accounts for round-trip losses and imports that don't line up with stored
  // charge. It's also capped by the battery's realistic yearly throughput.
  const suggested_kwh = importKwh > 2500 ? 10 : 7;
  const throughput = suggested_kwh * 300 * 0.9; // ~300 cycles/yr at 90% usable
  const recoverable = Math.min(exportKwh, importKwh, throughput) * 0.7;
  const annual = recoverable * (importRate - tariff.feed_in_eur_per_kwh);
  return {
    annual_eur: Math.round(annual / 10) * 10,
    exported_kwh: round(exportKwh),
    suggested_kwh,
  };
}

// ---- week-ahead energy outlook (from REAL timeseries data) -------------------

/**
 * The "week ahead" built from the household's ACTUAL next 7 days in the dataset:
 * daily solar production and outdoor temperature. We express each day's solar as
 * a "full-sun-equivalent hours" figure (daily PV kWh ÷ system kWp), the standard
 * specific-yield measure, and derive a good/ok/low rating and a sky icon from it.
 */
export function getEnergyOutlook(id: string, startISO = REFERENCE_NOW): WeatherOutlook {
  const h = getHousehold(id);
  const { records } = getTimeseries(id);
  const start = new Date(startISO.slice(0, 10) + "T00:00:00");
  const days: DayForecast[] = [];

  for (let i = 1; i <= 7; i++) {
    const d = new Date(start);
    d.setDate(d.getDate() + i);
    const iso = d.toISOString().slice(0, 10);
    const recs = records.filter((r) => r.timestamp.startsWith(iso));
    if (!recs.length) continue;

    let pv = 0;
    let temp = 0;
    for (const r of recs) {
      pv += r.pv_production_kw * STEP_HOURS;
      temp += r.outdoor_temp_c;
    }
    const sun = h.pv_kwp > 0 ? round(pv / h.pv_kwp, 1) : 0; // specific yield ≈ sun hours

    let icon: SkyIcon;
    let potential: DayForecast["solar_potential"];
    if (sun >= 4.5) {
      icon = "sun";
      potential = "high";
    } else if (sun >= 3) {
      icon = "partly";
      potential = "medium";
    } else if (sun >= 1.5) {
      icon = "cloud";
      potential = "medium";
    } else {
      icon = "rain";
      potential = "low";
    }

    days.push({
      date: iso,
      weekday: d.toLocaleDateString("en-US", { weekday: "short" }),
      temp_c: Math.round(temp / recs.length),
      sun_hours: sun,
      solar_potential: potential,
      icon,
    });
  }

  const avgSun = days.length
    ? round(days.reduce((a, d) => a + d.sun_hours, 0) / days.length, 1)
    : 0;
  const lowDays = days.filter((d) => d.solar_potential === "low").length;

  let recommendation: WeatherOutlook["recommendation"];
  const hasBattery = h.battery_kwh > 0;
  // value gap: using your own solar avoids buying at the grid price, vs only the
  // low feed-in rate if you export it. Used to explain "use it, don't sell it".
  const tariff = getTariff(h.tariff_id);
  const bills = getBills(id);
  const impKwh = bills.reduce((a, b) => a + b.grid_import_kwh, 0);
  const impCost = bills.reduce((a, b) => a + b.energy_cost_eur, 0);
  const importRate = impKwh > 0 ? impCost / impKwh : 0.3;
  const feedRate = tariff.feed_in_eur_per_kwh;
  const valueRatio = Math.max(2, Math.round(importRate / feedRate));

  if (avgSun < 2.5 || lowDays >= 3) {
    recommendation = {
      light: "red",
      title: hasBattery
        ? "Low-solar week, keep the battery for the evenings"
        : "Low-solar week, you'll lean on the grid",
      detail: `Your panels will make less this week (about ${avgSun}h of full sun a day in ${h.city}). ${
        hasBattery
          ? "Hold the battery's charge for evenings rather than exporting it cheaply, you'll buy less from the grid when prices are higher."
          : "Shift what you can into the sunny midday hours; the rest will come from the grid, so aim for the cheaper windows."
      }`,
    };
  } else if (avgSun < 4) {
    recommendation = {
      light: "yellow",
      title: "A mixed week, charge up on the sunny days",
      detail: `A mix of sun and cloud ahead in ${h.city} (about ${avgSun}h of full sun a day). ${
        hasBattery
          ? "Top the battery up on the bright days and lean on it when it's grey."
          : "Run heavy appliances on the sunnier days to use your own power."
      }`,
    };
  } else {
    recommendation = {
      light: "green",
      title: "Sunny week, make the most of your own solar",
      detail: `Lots of sun ahead in ${h.city} (about ${avgSun}h of full sun a day), so you'll have plenty of solar. Using it yourself is worth about ${valueRatio}× more than the feed-in payment (you skip buying at ~${Math.round(
        importRate * 100
      )}c/kWh, versus earning ~${Math.round(
        feedRate * 100
      )}c when you export). So run laundry, the dishwasher${
        h.ev_charger ? " and charge the car" : ""
      } around midday${
        hasBattery ? ", and let the battery store the rest for the evening" : ""
      }. Anything left over still earns you money going back to the grid.`,
    };
  }

  return { city: h.city, days, avg_sun_hours: avgSun, recommendation };
}

/** Compare the household's actual yearly cost against the alternative tariff. */
export interface TariffComparison {
  current_tariff_id: string;
  current_cost_eur: number;
  alternative_tariff_id: string;
  alternative_cost_eur: number;
  savings_eur: number; // positive => staying on current tariff is cheaper
  better: "current" | "alternative";
  note: string;
}

export function compareTariffs(id: string): TariffComparison {
  const h = getHousehold(id);
  const { records } = getTimeseries(id);
  const current = getTariff(h.tariff_id);
  const altId = h.tariff_id === "dynamic" ? "fixed" : "dynamic";
  const alt = getTariff(altId);

  let currentEnergy = 0;
  let altEnergy = 0;
  let exportKwh = 0;
  for (const r of records) {
    const importKwh = r.grid_import_kw * STEP_HOURS;
    exportKwh += r.grid_export_kw * STEP_HOURS;
    // current uses the embedded retail price
    currentEnergy += importKwh * r.price_eur_per_kwh;
    // alternative: if alt is fixed -> flat rate; if alt is dynamic -> embedded
    // dynamic price equals spot+adder, but our embedded price already reflects
    // the household's own tariff. For a fair counterfactual we approximate the
    // dynamic retail as (embedded price for dynamic homes). For fixed->dynamic
    // we rebuild from spot price.
    if (alt.type === "fixed_rate") {
      altEnergy += importKwh * (alt.energy_rate_eur_per_kwh ?? 0);
    } else {
      altEnergy += importKwh * dynamicRetailAt(r.timestamp, alt);
    }
  }

  const months = 12;
  const currentTotal =
    currentEnergy + current.base_fee_eur_per_month * months -
    exportKwh * current.feed_in_eur_per_kwh;
  const altTotal =
    altEnergy + alt.base_fee_eur_per_month * months -
    exportKwh * alt.feed_in_eur_per_kwh;

  const savings = round(altTotal - currentTotal); // >0 => current cheaper
  return {
    current_tariff_id: current.tariff_id,
    current_cost_eur: round(currentTotal),
    alternative_tariff_id: alt.tariff_id,
    alternative_cost_eur: round(altTotal),
    savings_eur: savings,
    better: savings >= 0 ? "current" : "alternative",
    note:
      savings >= 0
        ? `Staying on the ${current.name} tariff saves about €${savings} a year versus ${alt.name}.`
        : `Switching to ${alt.name} could save about €${Math.abs(savings)} a year.`,
  };
}

const _spotByTs = new Map<string, number>();
function dynamicRetailAt(timestamp: string, tariff: Tariff): number {
  if (_spotByTs.size === 0) {
    for (const p of getSpotPrices()) _spotByTs.set(p.timestamp, p.spot_price_eur_per_kwh);
  }
  const hourTs = timestamp.slice(0, 13) + ":00:00";
  const spot = _spotByTs.get(hourTs) ?? 0;
  return spot + (tariff.spot_adder_eur_per_kwh ?? 0);
}

// ---- personalized recommendations (the coach) -------------------------------

export type RecIcon = "bolt" | "ev" | "heatpump" | "battery" | "tariff" | "sun" | "alert";

export interface Recommendation {
  id: string;
  icon: RecIcon;
  tone: "good" | "warn" | "info";
  title: string;
  detail: string;
  saving?: string; // short money tag, e.g. "~€1.20/charge"
  priority: number; // higher = shown first
}

/** Price today at a given hour (HH), averaged over its quarter-hours. */
function priceAtHour(id: string, hour: number, date = REFERENCE_NOW.slice(0, 10)): number {
  const { records } = getTimeseries(id);
  const hh = String(hour).padStart(2, "0");
  const recs = records.filter((r) => r.timestamp.startsWith(date) && r.timestamp.slice(11, 13) === hh);
  if (!recs.length) return 0.3;
  return recs.reduce((a, r) => a + r.price_eur_per_kwh, 0) / recs.length;
}

function dayAvgPrice(id: string, date: string): number {
  const { records } = getTimeseries(id);
  const recs = records.filter((r) => r.timestamp.startsWith(date));
  if (!recs.length) return 0.3;
  return recs.reduce((a, r) => a + r.price_eur_per_kwh, 0) / recs.length;
}

function addDays(date: string, n: number): string {
  const d = new Date(date + "T00:00:00");
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

/** Sum a per-step kW field over a month, converted to kWh. */
function monthFieldSum(id: string, field: keyof TimeseriesRecord, month: string): number {
  const { records } = getTimeseries(id);
  let s = 0;
  for (const r of records) if (r.timestamp.startsWith(month)) s += (r[field] as number) * STEP_HOURS;
  return s;
}

/** The home's always-on (overnight) base load in kW. */
function overnightBaseload(id: string, date: string): number {
  const { records } = getTimeseries(id);
  const night = records.filter(
    (r) => r.timestamp.startsWith(date) && r.timestamp.slice(11, 13) < "05"
  );
  if (!night.length) return 0.1;
  return Math.min(...night.map((r) => r.house_load_kw));
}

function avgImportRate(id: string): number {
  const bills = getBills(id);
  const cost = bills.reduce((a, b) => a + b.energy_cost_eur, 0);
  const imp = bills.reduce((a, b) => a + b.grid_import_kwh, 0);
  return imp > 0 ? cost / imp : 0.3;
}

/**
 * A ranked, personalized action feed, the heart of the product. Every item is
 * derived from THIS household's assets, tariff, live state, anomalies, forecast
 * and bills, so two homes never see the same advice.
 */
export function getRecommendations(id: string, timestamp = REFERENCE_NOW): Recommendation[] {
  const h = getHousehold(id);
  const status = getTrafficStatus(id, timestamp);
  const [best] = getCheapestWindows(id, timestamp, 1);
  const recs: Recommendation[] = [];

  // 1. Live heat-pump anomaly (highest priority when active)
  if (h.heat_pump && anomalyActive(id, "heat pump", timestamp.slice(0, 10))) {
    recs.push({
      id: "hp-anomaly",
      icon: "alert",
      tone: "warn",
      title: "Your heat pump is using excess electricity",
      detail:
        "It's drawing more than the weather explains. Likely causes: a thermostat set too high, a defrost-cycle fault, or low refrigerant. Try: lower the target by 1°C, clear airflow around the outdoor unit, and book a service if it persists.",
      saving: "~€40/mo",
      priority: 100,
    });
  }

  // 2. Use free solar right now (when there's surplus)
  if (status.solar_surplus) {
    recs.push({
      id: "use-surplus-now",
      icon: "sun",
      tone: "good",
      title: "Run a big load now, it's free",
      detail: `Your panels are making more than the home needs${
        h.battery_kwh ? " and the battery's topped up" : ""
      }. Start the dishwasher or laundry now and it costs you almost nothing.`,
      saving: "free",
      priority: 80,
    });
  }

  // 3. EV: shift charging to the cheapest window (personalized saving)
  if (h.ev_charger && best) {
    const evening = priceAtHour(id, 19, timestamp.slice(0, 10));
    const sessionKwh = 11; // a typical top-up
    const perCharge = Math.max(0, (evening - best.price) * sessionKwh);
    if (perCharge > 0.3) {
      recs.push({
        id: "ev-shift",
        icon: "ev",
        tone: "info",
        title: `Charge the car around ${best.time}, not in the evening`,
        detail: `At ${best.time} power is ${(best.price * 100).toFixed(
          0
        )}c vs ${(evening * 100).toFixed(0)}c at 19:00. Set the wallbox to Eco and it waits for the cheap hour.`,
        saving: `~€${perCharge.toFixed(2)}/charge`,
        priority: 70,
      });
    }
  }

  // 4. Heat pump: pre-heat on free solar instead of an expensive evening
  if (h.heat_pump && !anomalyActive(id, "heat pump", timestamp.slice(0, 10))) {
    recs.push({
      id: "hp-preheat",
      icon: "heatpump",
      tone: "info",
      title: "Pre-heat around midday, coast in the evening",
      detail:
        "Warming the house while the sun is up uses your own free solar, so the heat pump pulls less from the grid when prices climb later.",
      priority: 40,
    });
  }

  // 5. Flexible loads to the cheapest window (dynamic tariff)
  if (h.tariff_id === "dynamic" && best && !status.solar_surplus) {
    recs.push({
      id: "shift-loads",
      icon: "bolt",
      tone: "info",
      title: `Cheapest power today is around ${best.time}`,
      detail: `Run the dishwasher, laundry or other flexible loads then, about ${(
        best.price * 100
      ).toFixed(0)}c/kWh, the lowest today.`,
      priority: 50,
    });
  }

  // 6. Battery upsell for homes without one
  const battery = getBatteryRecommendation(id);
  if (battery) {
    recs.push({
      id: "add-battery",
      icon: "battery",
      tone: "info",
      title: "A home battery would pay you back",
      detail: `You sell ${battery.exported_kwh.toFixed(
        0
      )} kWh of spare solar a year for a few cents. A battery would store it for the evening instead.`,
      saving: `~€${battery.annual_eur}/yr`,
      priority: 60,
    });
  }

  // 7. Tariff switch (only if it actually helps)
  const tariff = compareTariffs(id);
  if (tariff.better === "alternative") {
    recs.push({
      id: "switch-tariff",
      icon: "tariff",
      tone: "info",
      title: "A different tariff could be cheaper",
      detail: tariff.note,
      saving: `~€${Math.abs(tariff.savings_eur)}/yr`,
      priority: 65,
    });
  }

  // 8. Rising bill heads-up
  const cmp = getBillComparison(id, timestamp.slice(0, 7));
  if (cmp.verdict === "worse") {
    recs.push({
      id: "bill-rising",
      icon: "alert",
      tone: "warn",
      title: "Your bill is trending higher this month",
      detail: `On track for about €${cmp.delta_eur < 0 ? Math.abs(cmp.delta_eur) : 0} more than your last two months. Shifting loads to cheap or sunny hours brings it back down.`,
      priority: 55,
    });
  }

  // --- forecast-driven nudges (from the real next-7-days data) ---
  const outlook = getEnergyOutlook(id, timestamp);
  const temps = outlook.days.map((d) => d.temp_c);
  const maxTemp = temps.length ? Math.max(...temps) : 0;
  const minTemp = temps.length ? Math.min(...temps) : 0;

  // 9. Hot week ahead -> cooling load up
  if (maxTemp >= 27) {
    recs.push({
      id: "weather-hot",
      icon: "sun",
      tone: "info",
      title: "Hot week ahead, watch your cooling",
      detail: `Up to ${Math.round(
        maxTemp
      )}°C next week. Fans, fridges and any air-conditioning work harder, which can nudge your bill up, run them on free midday solar where you can.`,
      priority: 46,
    });
  }

  // 10. Cold week ahead -> heating costs up
  if (minTemp <= 4 && h.heat_pump) {
    recs.push({
      id: "weather-cold",
      icon: "heatpump",
      tone: "warn",
      title: "Cold snap next week, heating will cost more",
      detail: `Lows around ${Math.round(
        minTemp
      )}°C are coming, so your heat pump will run more. Pre-heat during sunny midday hours to lean on free solar instead of the evening grid.`,
      priority: 48,
    });
  }

  // 11. Low-solar / rainy week -> keep your surplus, don't sell it
  if (outlook.recommendation.light === "red") {
    recs.push({
      id: "rainy-week",
      icon: "battery",
      tone: "info",
      title: "Low-solar week, get the most from what you make",
      detail: h.battery_kwh
        ? "Cloudy days ahead mean less solar. Save the battery's charge for the evening so you buy less from the grid when it's pricey."
        : "Cloudy days ahead mean less solar. Try to use what you make during the day, since buying it back from the grid later costs more.",
      priority: 58,
    });
  }

  // 12. Dynamic tariff: prices look higher tomorrow -> review / shift
  if (h.tariff_id === "dynamic") {
    const todayAvg = dayAvgPrice(id, timestamp.slice(0, 10));
    const tomAvg = dayAvgPrice(id, addDays(timestamp.slice(0, 10), 1));
    if (tomAvg > todayAvg * 1.12) {
      recs.push({
        id: "tariff-tomorrow",
        icon: "tariff",
        tone: "info",
        title: "Power looks pricier tomorrow",
        detail: `Tomorrow averages about ${(tomAvg * 100).toFixed(0)}c/kWh vs ${(
          todayAvg * 100
        ).toFixed(0)}c today. Run flexible loads today, or tap to review your tariff.`,
        priority: 52,
      });
    }
  }

  // 13. Battery is doing well (positive reinforcement)
  if (h.battery_kwh > 0) {
    const dischargeKwh = monthFieldSum(id, "battery_discharge_kw", timestamp.slice(0, 7));
    if (dischargeKwh > 25) {
      recs.push({
        id: "battery-healthy",
        icon: "battery",
        tone: "good",
        title: "Your battery is pulling its weight",
        detail: `It's powered about ${dischargeKwh.toFixed(
          0
        )} kWh of your home this month from stored solar, energy you didn't buy from the grid.`,
        priority: 36,
      });
    }
  }

  // 14. Efficient appliance suggestion (high always-on load)
  const baseMonthKwh = overnightBaseload(id, timestamp.slice(0, 10)) * 24 * 30;
  if (baseMonthKwh > 55) {
    const saveKwh = Math.round(baseMonthKwh * 0.12);
    const saveEur = Math.round(saveKwh * avgImportRate(id));
    recs.push({
      id: "efficient-appliance",
      icon: "bolt",
      tone: "info",
      title: "An efficient fridge could trim your always-on load",
      detail: `Your home draws about ${baseMonthKwh.toFixed(
        0
      )} kWh/month around the clock. Swapping an old fridge or freezer for an A-rated model could save roughly ${saveKwh} kWh a month.`,
      saving: `~€${saveEur}/mo`,
      priority: 30,
    });
  }

  return recs.sort((a, b) => b.priority - a.priority);
}

// ---- utils -------------------------------------------------------------------

function round(n: number, dp = 2): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}
